"""empty message

Revision ID: 1ac6a3006896
Revises: 
Create Date: 2024-09-06 19:23:09.697272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac6a3006896'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('email_hash', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('unverified_phone_number', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('phone_number_hash', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('password_hash', sa.String(), nullable=False))
    op.drop_constraint('user_table_telegram_id_key', 'user_table', type_='unique')
    op.drop_constraint('user_table_verified_email_key', 'user_table', type_='unique')
    op.create_unique_constraint(None, 'user_table', ['email'])
    op.create_unique_constraint(None, 'user_table', ['phone_number'])
    op.drop_column('user_table', 'verified_email')
    op.drop_column('user_table', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('verified_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'user_table', type_='unique')
    op.create_unique_constraint('user_table_verified_email_key', 'user_table', ['verified_email'])
    op.create_unique_constraint('user_table_telegram_id_key', 'user_table', ['telegram_id'])
    op.drop_column('user_table', 'password_hash')
    op.drop_column('user_table', 'phone_number_hash')
    op.drop_column('user_table', 'unverified_phone_number')
    op.drop_column('user_table', 'email_hash')
    op.drop_column('user_table', 'email')
    # ### end Alembic commands ###
