"""empty message

Revision ID: 1e0dce4a84ed
Revises: f31c07dea916
Create Date: 2024-09-11 10:54:42.910688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0dce4a84ed'
down_revision: Union[str, None] = 'f31c07dea916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_table_phone_number_code_id_fkey', 'user_table', type_='foreignkey')
    op.drop_constraint('user_table_email_code_id_fkey', 'user_table', type_='foreignkey')
    op.drop_column('user_table', 'email_code_id')
    op.drop_column('user_table', 'phone_number_code_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('phone_number_code_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('email_code_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_table_email_code_id_fkey', 'user_table', 'code_table', ['email_code_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('user_table_phone_number_code_id_fkey', 'user_table', 'code_table', ['phone_number_code_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
