"""empty message

Revision ID: 31f673ba6a93
Revises: 8f8a8edc46a4
Create Date: 2024-09-10 19:44:39.815123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31f673ba6a93'
down_revision: Union[str, None] = '8f8a8edc46a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_table', sa.Column('expire_datetime', sa.DateTime(), nullable=False))
    op.drop_column('code_table', 'expire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_table', sa.Column('expire', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('code_table', 'expire_datetime')
    # ### end Alembic commands ###
