"""empty message

Revision ID: 546f0065e55d
Revises: b0e161d25f83
Create Date: 2024-09-10 17:10:03.793520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546f0065e55d'
down_revision: Union[str, None] = 'b0e161d25f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'email_hash')
    op.drop_column('user_table', 'unverified_phone_number')
    op.drop_column('user_table', 'phone_number_hash')
    op.drop_column('user_table', 'unverified_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('unverified_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('phone_number_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('unverified_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('email_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
