"""empty message

Revision ID: e91a3fcd3001
Revises: 1ac6a3006896
Create Date: 2024-09-09 13:41:40.307108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91a3fcd3001'
down_revision: Union[str, None] = '1ac6a3006896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_combination_table',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_id'], ['combination_table.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_combination_table')
    # ### end Alembic commands ###
