"""empty message

Revision ID: f31c07dea916
Revises: 31f673ba6a93
Create Date: 2024-09-11 10:50:28.736391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31c07dea916'
down_revision: Union[str, None] = '31f673ba6a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_table', 'attempts')
    op.add_column('user_table', sa.Column('expire_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'expire_datetime')
    op.add_column('code_table', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
