"""added index and default to uuid

Revision ID: f531a3ff5fba
Revises: 9c690e210125
Create Date: 2024-10-02 19:35:58.233809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f531a3ff5fba'
down_revision: Union[str, None] = '9c690e210125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_code_table_id'), 'code_table', ['id'], unique=False)
    op.create_index(op.f('ix_collection_table_id'), 'collection_table', ['id'], unique=False)
    op.create_index(op.f('ix_combination_table_id'), 'combination_table', ['id'], unique=False)
    op.create_index(op.f('ix_product_table_id'), 'product_table', ['id'], unique=False)
    op.create_index(op.f('ix_user_table_id'), 'user_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_id'), table_name='user_table')
    op.drop_index(op.f('ix_product_table_id'), table_name='product_table')
    op.drop_index(op.f('ix_combination_table_id'), table_name='combination_table')
    op.drop_index(op.f('ix_collection_table_id'), table_name='collection_table')
    op.drop_index(op.f('ix_code_table_id'), table_name='code_table')
    # ### end Alembic commands ###
